LocadoraDeVeiculos.Web/Models/VeiculoViewModels.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace LocadoraDeVeiculos.Web.Models;

public class FormularioVeiculoViewModel
{
    [Required(ErrorMessage = "O modelo é obrigatório")]
    [MinLength(3, ErrorMessage = "O modelo deve conter ao menos 3 caracteres")]
    public string Modelo { get; set; }

    [Required(ErrorMessage = "A marca é obrigatória")]
    [MinLength(2, ErrorMessage = "A marca deve conter ao menos 2 caracteres")]
    public string Marca { get; set; }

    [Required(ErrorMessage = "O tipo de combustível é obrigatório")]
    public int TipoCombustivel { get; set; }

    [Required(ErrorMessage = "A capacidade do tanque é obrigatória")]
    [Range(1, int.MaxValue, ErrorMessage = "A capacidade do tanque deve ser maior que 0")]
    public int CapacidadeTanque { get; set; }

    [Required(ErrorMessage = "O grupo de veículos é obrigatório")]
    public int GrupoDeAutomoveisId { get; set; }

    public IEnumerable<SelectListItem>? GrupoDeAutomoveis { get; set; }
}

public class InserirVeiculoViewModel : FormularioVeiculoViewModel { }

public class EditarVeiculoViewModel : FormularioVeiculoViewModel
{
    public int Id { get; set; }
}

public class ListarVeiculoViewModel
{
    public int Id { get; set; }
    public string Modelo { get; set; }
    public string Marca { get; set; }
    public string TipoCombustivel { get; set; }
    public int CapacidadeTanque { get; set; }
    public string GrupoDeAutomoveis { get; set; }
}

public class DetalhesVeiculoViewModel
{
    public int Id { get; set; }
    public string Modelo { get; set; }
    public string Marca { get; set; }
    public string TipoCombustivel { get; set; }
    public int CapacidadeTanque { get; set; }
    public string GrupoDeAutomoveis { get; set; }
}

LocadoraDeVeiculos.Web/Controllers/VeiculoController.cs
using AutoMapper;
using LocadoraDeVeiculos.Dominio.ModuloCliente;
using LocadoraDeVeiculos.Dominio.ModuloVeiculo;
using LocadoraDeVeiculos.Service.Servicos;
using LocadoraDeVeiculos.Web.Aplicacao.Servicos;
using LocadoraDeVeiculos.Web.Controllers;
using LocadoraDeVeiculos.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LocadoraDeVeiculos.WebApp.Controllers;

public class VeiculoController : WebControllerBase
{
    private readonly VeiculoService servico;
    private readonly GrupoDeAutomoveisService servicoGrupos;
    private readonly IMapper mapeador;

    public VeiculoController(
        VeiculoService servico,
        GrupoDeAutomoveisService servicoGrupos,
        IMapper mapeador
    )
    {
        this.servico = servico;
        this.servicoGrupos = servicoGrupos;
        this.mapeador = mapeador;
    }

    public IActionResult Listar()
    {
        var resultado = servico.SelecionarTodos(UsuarioId.GetValueOrDefault());

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction("Index", "Home");
        }

        var veiculos = resultado.Value;

        var listarVeiculosVm = mapeador.Map<IEnumerable<ListarVeiculoViewModel>>(veiculos);

        return View(listarVeiculosVm);
    }

    public IActionResult Inserir()
    {
        return View(CarregarDadosFormulario());
    }

    [HttpPost]
    public IActionResult Inserir(InserirVeiculoViewModel inserirVm)
    {
        if (!ModelState.IsValid)
            return View(CarregarDadosFormulario(inserirVm));

        var veiculo = mapeador.Map<Veiculo>(inserirVm);

        veiculo.UsuarioId = UsuarioId.GetValueOrDefault();

        var resultado = servico.Inserir(veiculo);


        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{veiculo.Id}] foi inserido com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult Editar(int id)
    {
        var resultado = servico.SelecionarPorId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var resultadoGrupos = servicoGrupos.SelecionarTodos(1);

        if (resultadoGrupos.IsFailed)
        {
            ApresentarMensagemFalha(resultadoGrupos.ToResult());

            return null;
        }

        var veiculo = resultado.Value;

        var editarVm = mapeador.Map<EditarVeiculoViewModel>(veiculo);

        var gruposDisponiveis = resultadoGrupos.Value;

        editarVm.GrupoDeAutomoveis = gruposDisponiveis
            .Select(g => new SelectListItem(g.Nome, g.Id.ToString()));

        return View(editarVm);
    }

    [HttpPost]
    public IActionResult Editar(EditarVeiculoViewModel editarVm)
    {
        if (!ModelState.IsValid)
            return View(CarregarDadosFormulario(editarVm));

        var veiculo = mapeador.Map<Veiculo>(editarVm);

        var resultado = servico.Editar(veiculo);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{veiculo.Id}] foi editado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult Excluir(int id)
    {
        var resultado = servico.SelecionarPorId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var veiculo = resultado.Value;

        var detalhesVm = mapeador.Map<DetalhesVeiculoViewModel>(veiculo);

        return View(detalhesVm);
    }

    [HttpPost]
    public IActionResult Excluir(DetalhesVeiculoViewModel detalhesVm)
    {
        var resultado = servico.Excluir(detalhesVm.Id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{detalhesVm.Id}] foi excluído com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult Detalhes(int id)
    {
        var resultado = servico.SelecionarPorId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var veiculo = resultado.Value;

        var detalhesVm = mapeador.Map<DetalhesVeiculoViewModel>(veiculo);

        return View(detalhesVm);
    }

    private FormularioVeiculoViewModel? CarregarDadosFormulario(
        FormularioVeiculoViewModel? dadosPrevios = null)
    {
        var resultadoGrupos = servicoGrupos.SelecionarTodos(1);

        if (resultadoGrupos.IsFailed)
        {
            ApresentarMensagemFalha(resultadoGrupos.ToResult());

            return null;
        }

        var gruposDisponiveis = resultadoGrupos.Value;

        if (dadosPrevios is null)
        {
            var formularioVm = new FormularioVeiculoViewModel
            {
                GrupoDeAutomoveis = gruposDisponiveis
                    .Select(g => new SelectListItem(g.Nome, g.Id.ToString()))
            };

            return formularioVm;
        }

        dadosPrevios.GrupoDeAutomoveis = gruposDisponiveis
            .Select(g => new SelectListItem(g.Nome, g.Id.ToString()));

        return dadosPrevios;
    }
}

LocadoraDeVeiculos.Web/Views/Veiculo/Detalhes.cshtml
@model DetalhesVeiculoViewModel

@{
    ViewBag.Title = "Detalhes do Veículo";
}

<div class="col">
    <partial name="_Informacoes" model="Model"></partial>

    <a asp-action="Listar" class="btn btn-outline-primary px-5 mt-5">
        <i class="bi bi-arrow-return-left me-1"></i>
        Voltar
    </a>
</div>

LocadoraDeVeiculos.Web/Views/Veiculo/Editar.cshtml
@using LocadoraDeVeiculos.Dominio.ModuloVeiculo

@model FormularioVeiculoViewModel

@{
    ViewBag.Title = "Editar Veículo";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="Editar">
            <div>
                <label class="control-label fw-semibold mb-1">Modelo</label>
                <input class="form-control mb-1" asp-for="Modelo" />
                <span class="text-danger fs-6" asp-validation-for="Modelo"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Marca</label>
                <input class="form-control mb-1" asp-for="Marca" />
                <span class="text-danger fs-6" asp-validation-for="Marca"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Tipo de Combustível</label>
                <select class="form-control mb-1" asp-for="TipoCombustivel" asp-items="Html.GetEnumSelectList<TipoCombustivel>()"></select>
                <span class="text-danger fs-6" asp-validation-for="TipoCombustivel"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Capacidade do Tanque</label>
                <input class="form-control mb-1" asp-for="CapacidadeTanque" type="number" />
                <span class="text-danger fs-6" asp-validation-for="CapacidadeTanque"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Grupo de Veículos</label>
                <select class="form-control mb-1" asp-for="GrupoDeAutomoveisId" asp-items="Model.GrupoDeAutomoveis"></select>
                <span class="text-danger fs-6" asp-validation-for="GrupoDeAutomoveisId"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraDeVeiculos.Web/Views/Veiculo/Excluir.cshtml
@model DetalhesVeiculoViewModel

@{
    ViewBag.Title = "Excluir Veículo";
}

<div class="col">
    <partial name="_Informacoes" model="Model"></partial>

    <form class="d-grid gap-2 d-md-block mt-5" asp-action="Excluir">
        <button class="btn btn-danger px-5">
            <i class="bi bi-trash-fill me-1"></i>
            Confirmar
        </button>

        <a class="btn btn-outline-primary px-5" asp-action="Listar">
            <i class="bi bi-arrow-return-left me-1"></i>
            Voltar
        </a>
    </form>
</div>

LocadoraDeVeiculos.Web/Views/Veiculo/Inserir.cshtml
@using LocadoraDeVeiculos.Dominio.ModuloVeiculo

@model FormularioVeiculoViewModel

@{
    ViewBag.Title = "Inserir Veículo";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="Inserir">
            <div>
                <label class="control-label fw-semibold mb-1">Modelo</label>
                <input class="form-control mb-1" asp-for="Modelo" />
                <span class="text-danger fs-6" asp-validation-for="Modelo"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Marca</label>
                <input class="form-control mb-1" asp-for="Marca" />
                <span class="text-danger fs-6" asp-validation-for="Marca"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Tipo de Combustível</label>
                <select class="form-control mb-1" asp-for="TipoCombustivel" asp-items="Html.GetEnumSelectList<TipoCombustivel>()"></select>
                <span class="text-danger fs-6" asp-validation-for="TipoCombustivel"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Capacidade do Tanque</label>
                <input class="form-control mb-1" asp-for="CapacidadeTanque" type="number" />
                <span class="text-danger fs-6" asp-validation-for="CapacidadeTanque"></span>
            </div>

            <div>
                <label class="control-label fw-semibold mb-1">Grupo de Veículos</label>
                <select class="form-control mb-1" asp-for="GrupoDeAutomoveisId" asp-items="Model.GrupoDeAutomoveis"></select>
                <span class="text-danger fs-6" asp-validation-for="GrupoDeAutomoveisId"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>
<script>
    function formatarPreco(element) {
        let valor = element.value;
        valor = valor.replace(/\D/g, "");
        valor = (valor / 100).toFixed(2) + ""; 
        valor = valor.replace(".", ","); 
        valor = valor.replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1."); 
        element.value = valor;
    }
</script>

LocadoraDeVeiculos.Web/Views/Veiculo/Listar.cshtml
@model IEnumerable<ListarVeiculoViewModel>

@{
    ViewBag.Title = "Listagem de Veículos";
}

<div class="col">

    <a class="btn btn-primary px-4 mt-3" asp-controller="Veiculo" asp-action="Inserir">
        <i class="bi bi-circle-add"></i>
        Inserir Novo Veículo
    </a>

    <div class="row gap-2 my-3 my-xl-5">
        @foreach (var veiculoVm in Model)
        {
            <div class="card col-lg-4 col-xl-3">
                <div class="card-header bg-transparent d-flex justify-content-between align-items-center">
                    <h5 class="p-0">@veiculoVm.Id</h5>

                    <div class="text-end d-flex align-items-center gap-3">
                        <a title="Detalhes"
                           class="text-info-emphasis fs-5"
                           href="/Veiculo/Detalhes/@veiculoVm.Id">
                            <i class="bi bi-search"></i>
                        </a>
                        <a title="Editar"
                           class="text-info-emphasis fs-5"
                           href="/Veiculo/Editar/@veiculoVm.Id">
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                        <a title="Excluir"
                           class="text-info-emphasis fs-5" href="/Veiculo/Excluir/@veiculoVm.Id">
                            <i class="bi bi-trash-fill"></i>
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <h5 class="card-title">@veiculoVm.Modelo</h5>
                    <p class="card-text">
                        Marca: @veiculoVm.Marca <br />
                        Tipo de Combustível: @veiculoVm.TipoCombustivel <br />
                        Capacidade do Tanque: @veiculoVm.CapacidadeTanque L
                    </p>
                </div>
            </div>
        }
    </div>
</div>

LocadoraDeVeiculos.Web/Views/Veiculo/_Informacoes.cshtml
@model DetalhesVeiculoViewModel

<div class="row gap-3 my-3 my-xl-5">
    <label class="fs-4"><strong>Modelo:</strong> @Model.Modelo</label>

    <label class="fs-4"><strong>Marca:</strong> @Model.Marca</label>

    <label class="fs-4"><strong>Tipo de Combustível:</strong> @Model.TipoCombustivel</label>

    <label class="fs-4"><strong>Capacidade do Tanque:</strong> @Model.CapacidadeTanque L</label>

    <label class="fs-4"><strong>Grupo de Veículos:</strong> @Model.GrupoDeAutomoveis</label>

    <label class="fs-5"><strong>Id:</strong> [@Model.Id]</label>
</div>