LocadoraDeVeiculos.Web/Models/AluguelViewModels.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using LocadoraDeVeiculos.Dominio.ModuloLocacao;

namespace LocadoraDeVeiculos.Web.Models;

public class FormularioAluguelViewModel
{
    [Required(ErrorMessage = "O cliente é obrigatório")]
    public int ClienteId { get; set; }

    [Required(ErrorMessage = "O veículo é obrigatório")]
    public int VeiculoId { get; set; }

    [Required(ErrorMessage = "O condutor é obrigatório")]
    public int CondutorId { get; set; }

    [Required(ErrorMessage = "O tipo de plano é obrigatório")]
    public TipoPlanoCobrancaEnum TipoPlano { get; set; }

    [Required(ErrorMessage = "O marcador de combustível é obrigatório")]
    public MarcadorCombustivelEnum MarcadorCombustivel { get; set; }

    [Required(ErrorMessage = "A quilometragem percorrida é obrigatória")]
    [Range(0, int.MaxValue, ErrorMessage = "A quilometragem percorrida deve ser maior ou igual a 0")]
    public int QuilometragemPercorrida { get; set; }

    [Required(ErrorMessage = "A data da locação é obrigatória")]
    [DataType(DataType.Date)]
    public DateTime DataLocacao { get; set; }

    [Required(ErrorMessage = "A data prevista de devolução é obrigatória")]
    [DataType(DataType.Date)]
    public DateTime DevolucaoPrevista { get; set; }

    public IEnumerable<int> TaxasSelecionadas { get; set; }

    public IEnumerable<SelectListItem>? Clientes { get; set; }
    public IEnumerable<SelectListItem>? Veiculos { get; set; }
    public IEnumerable<SelectListItem>? Condutores { get; set; }
    public IEnumerable<SelectListItem>? Taxas { get; set; }

    public FormularioAluguelViewModel()
    {
        DataLocacao = DateTime.Now;
        DevolucaoPrevista = DateTime.Now.AddDays(1);
       
    }
}

public class InserirAluguelViewModel : FormularioAluguelViewModel
{
}

public class EditarAluguelViewModel : FormularioAluguelViewModel
{
    public int Id { get; set; }
}

public class RealizarDevolucaoViewModel : FormularioAluguelViewModel
{
    public int Id { get; set; }
}

public class ListarAluguelViewModel
{
    public int Id { get; set; }
    public string Cliente { get; set; }
    public string Veiculo { get; set; }
    public string Condutor { get; set; }
    public string TipoPlano { get; set; }
    public int QuilometragemPercorrida { get; set; }
    public DateTime DataLocacao { get; set; }
    public DateTime DevolucaoPrevista { get; set; }
    public DateTime? DataDevolucao { get; set; }
}

public class DetalhesAluguelViewModel
{
    public int Id { get; set; }
    public string Cliente { get; set; }
    public string Veiculo { get; set; }
    public string Condutor { get; set; }
    public string TipoPlano { get; set; }
    public string MarcadorCombustivel { get; set; }
    public int QuilometragemPercorrida { get; set; }
    public DateTime DataLocacao { get; set; }
    public DateTime DevolucaoPrevista { get; set; }
    public DateTime? DataDevolucao { get; set; }
}

LocadoraDeVeiculos.Web/Controllers/AluguelController.cs
using AutoMapper;
using LocadoraDeVeiculos.Dominio.ModuloAluguel;
using LocadoraDeVeiculos.Dominio.ModuloCliente;
using LocadoraDeVeiculos.Dominio.ModuloTaxaEServico;
using LocadoraDeVeiculos.Infraestrutura.ModuloTaxaEServico;
using LocadoraDeVeiculos.Service.Servicos;
using LocadoraDeVeiculos.Web.Aplicacao.Servicos;
using LocadoraDeVeiculos.Web.Controllers;
using LocadoraDeVeiculos.Web.Dominio.ModuloPlanoCobranca;
using LocadoraDeVeiculos.Web.Models;
using LocadoraDeVeiculos.Web.Service.Servicos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LocadoraDeVeiculos.WebApp.Controllers;

public class AluguelController : WebControllerBase
{
    private readonly AluguelService AluguelService;
    private readonly VeiculoService VeiculoService;
    private readonly GrupoDeAutomoveisService GrupoDeAutomoveisService;
    private readonly CondutorService CondutorService;
    private readonly TaxaEServicoService TaxaEServicoService;
    private readonly ClienteService ClienteService;
    private readonly PlanoCobrancaService PlanoService;
    private readonly IMapper mapeador;

    public AluguelController(
        AluguelService AluguelService,
        VeiculoService VeiculoService,
        GrupoDeAutomoveisService GrupoDeAutomoveisService,
        CondutorService CondutorService,
        TaxaEServicoService TaxaEServicoService,
        ClienteService ClienteService,
        PlanoCobrancaService PlanoService,
        IMapper mapeador
    )
    {
        this.AluguelService = AluguelService;
        this.VeiculoService = VeiculoService;
        this.GrupoDeAutomoveisService = GrupoDeAutomoveisService;
        this.CondutorService = CondutorService;
        this.TaxaEServicoService = TaxaEServicoService;
        this.ClienteService = ClienteService;
        this.PlanoService = PlanoService;
        this.mapeador = mapeador;
    }

    public IActionResult Listar()
    {
        var resultado = AluguelService.SelecionarTodos(UsuarioId.GetValueOrDefault());

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction("Index", "Home");
        }

        var locacoes = resultado.Value;

        var listarLocacoesVm = mapeador.Map<IEnumerable<ListarAluguelViewModel>>(locacoes);

        //foreach (var v in listarLocacoesVm)
        //{
        //    v.Veiculo = AluguelService.SelecionarPorIdObjeto();
        //    v.Cliente = AluguelService.SelecionarPorIdObjeto().Cliente.Nome;
        //    v.DataLocacao = AluguelService.SelecionarPorIdObjeto(v.Id).DataSaida;
        //}

        //Ficou uma bosta q nao funciona nada nesse aluguel , tenho q refazer tudo 

        return View(listarLocacoesVm);
    }

    public IActionResult Inserir()
    {
        return View(CarregarDadosFormulario());
    }

    [HttpPost]
    public IActionResult Inserir(InserirAluguelViewModel inserirVm)
    {

        if (!ModelState.IsValid)
            return View(CarregarDadosFormulario(inserirVm));

        Aluguel aluguel = new Aluguel(
            ClienteService.SelecionarPorIdObjeto(inserirVm.ClienteId),
            CondutorService.SelecionarPorIdObjeto(inserirVm.CondutorId),
            GrupoDeAutomoveisService.SelecionarPorIdObjeto(VeiculoService.SelecionarPorIdObjeto(inserirVm.VeiculoId).GrupoDeAutomoveisId),
            VeiculoService.SelecionarPorIdObjeto(inserirVm.VeiculoId),
            inserirVm.DataLocacao,
            inserirVm.DevolucaoPrevista, 
            1000,
            0,
            PlanoService.SelecionarObjeto(VeiculoService.SelecionarPorIdObjeto(inserirVm.VeiculoId)),
           TaxaEServicoService.SelecionarPorIdsObjetos(inserirVm.TaxasSelecionadas.ToArray(), VeiculoService.SelecionarPorIdObjeto(inserirVm.VeiculoId)),
            true
          );
        aluguel.UsuarioId = ClienteService.SelecionarPorIdObjeto(inserirVm.ClienteId).UsuarioId;
        var resultado = AluguelService.Inserir(aluguel);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{aluguel.Id}] foi inserido com sucesso!");

        return RedirectToAction(nameof(Listar));
    }
    public IActionResult Editar(int id)
    {
        var resultado = AluguelService.SelecionarPorId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var cliente = resultado.Value;

        var editarVm = mapeador.Map<EditarAluguelViewModel>(cliente);

        return View(editarVm);
    }

    [HttpPost]
    public IActionResult Editar(EditarAluguelViewModel editarVm)
    {
        if (!ModelState.IsValid)
            return View();

        var aluguel = mapeador.Map<Aluguel>(editarVm);

        var resultado = AluguelService.Editar(aluguel);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"O registro ID [{aluguel.Id}] foi editado com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    public IActionResult RealizarDevolucao(int id)
    {
        var resultado = AluguelService.SelecionarPorId(id);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        var locacao = resultado.Value;

        var devolucaoVm = mapeador.Map<RealizarDevolucaoViewModel>(locacao);

        return View(devolucaoVm);
    }

    [HttpPost]
    public IActionResult RealizarDevolucao(RealizarDevolucaoViewModel devolucaoVm)
    {
        var locacaoOriginal = AluguelService.SelecionarPorId(devolucaoVm.Id).Value;

        var locacaoAtualizada = mapeador.Map<RealizarDevolucaoViewModel, Aluguel>(devolucaoVm, locacaoOriginal);

        var resultado = AluguelService.RealizarDevolucao(locacaoAtualizada);

        if (resultado.IsFailed)
        {
            ApresentarMensagemFalha(resultado.ToResult());

            return RedirectToAction(nameof(Listar));
        }

        ApresentarMensagemSucesso($"A locação ID [{locacaoAtualizada.Id}] foi concluída com sucesso!");

        return RedirectToAction(nameof(Listar));
    }

    private InserirAluguelViewModel CarregarDadosFormulario(InserirAluguelViewModel? formularioVm = null)
    {
        var condutores = CondutorService.SelecionarTodos(UsuarioId.GetValueOrDefault()).Value;
        var veiculos = VeiculoService.SelecionarTodos(UsuarioId.GetValueOrDefault()).Value;
        var taxas = TaxaEServicoService.SelecionarTodos(UsuarioId.GetValueOrDefault()).Value;
        var clientes = ClienteService.SelecionarTodos(UsuarioId.GetValueOrDefault()).Value;

        if (formularioVm is null)
            formularioVm = new InserirAluguelViewModel();

        formularioVm.Condutores =
            condutores.Select(c => new SelectListItem(c.Nome, c.Id.ToString()));

        formularioVm.Veiculos =
            veiculos.Select(c => new SelectListItem(c.Modelo, c.Id.ToString()));

        formularioVm.Taxas =
            taxas.Select(c => new SelectListItem(c.Nome, c.Id.ToString()));

        formularioVm.Clientes =
            clientes.Select(c => new SelectListItem(c.Nome, c.Id.ToString()));

        return formularioVm;
    }
}

LocadoraDeVeiculos.Web/Views/Aluguel/Detalhes.cshtml
@model DetalhesAluguelViewModel

@{
    ViewBag.Title = "Detalhes da Locação";
}

<div class="col">
    <partial name="_Informacoes" model="Model"></partial>

    <a asp-action="Listar" class="btn btn-outline-primary px-5 mt-5">
        <i class="bi bi-arrow-return-left me-1"></i>
        Voltar
    </a>
</div>

LocadoraDeVeiculos.Web/Views/Aluguel/Editar.cshtml
@using LocadoraDeVeiculos.Dominio.ModuloLocacao
@using Microsoft.AspNetCore.Mvc.TagHelpers

@model EditarAluguelViewModel

@{
    ViewBag.Title = "Editar Aluguel";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="Editar">
            
            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Veículo</label>
                <select class="form-control mb-1" asp-for="VeiculoId" asp-items="Model.Veiculos">
                    @if (Model.Veiculos is null || !Model.Veiculos.Any())
                    {
                        <option value="0" disabled>Nenhum veículo disponível</option>
                    }
                </select>
                <span class="text-danger fs-6" asp-validation-for="VeiculoId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Condutor</label>
                <select class="form-control mb-1" asp-for="CondutorId" asp-items="Model.Condutores">
                    @if (Model.Condutores is null || !Model.Condutores.Any())
                    {
                        <option value="0" disabled>Nenhum condutor disponível</option>
                    }
                </select>
                <span class="text-danger fs-6" asp-validation-for="CondutorId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Tipo de Plano</label>
                <select class="form-control mb-1" asp-for="TipoPlano" asp-items="Html.GetEnumSelectList<TipoPlanoCobrancaEnum>()"></select>
                <span class="text-danger fs-6" asp-validation-for="TipoPlano"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Marcador de Combustível</label>
                <select class="form-control mb-1" asp-for="MarcadorCombustivel" asp-items="Html.GetEnumSelectList<MarcadorCombustivelEnum>()" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="MarcadorCombustivel"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Quilometragem Percorrida</label>
                <input class="form-control mb-1" asp-for="QuilometragemPercorrida" type="number" readonly/>
                <span class="text-danger fs-6" asp-validation-for="QuilometragemPercorrida"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Data da Locação</label>
                <input class="form-control mb-1" asp-for="DataLocacao" type="date" min="@DateTime.Today"/>
                <span class="text-danger fs-6" asp-validation-for="DataLocacao"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Data Prevista de Devolução</label>
                <input class="form-control mb-1" asp-for="DevolucaoPrevista" type="date" min="@DateTime.Today"/>
                <span class="text-danger fs-6" asp-validation-for="DevolucaoPrevista"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Taxas Selecionadas</label>
                <select class="form-control mb-1" asp-for="TaxasSelecionadas" asp-items="Model.Taxas" multiple></select>
                <span class="text-danger fs-6" asp-validation-for="TaxasSelecionadas"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraDeVeiculos.Web/Views/Aluguel/Inserir.cshtml
@using LocadoraDeVeiculos.Dominio.ModuloLocacao
@using Microsoft.AspNetCore.Mvc.TagHelpers

@model InserirAluguelViewModel

@{
    ViewBag.Title = "Inserir Aluguel";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="Inserir">
            
            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Cliente</label>
                <select class="form-control mb-1" asp-for="ClienteId" asp-items="Model.Clientes">
                    @if (Model.Clientes is null || !Model.Clientes.Any())
                    {
                        <option value="0" disabled>Nenhum cliente disponível</option>
                    }
                </select>
                <span class="text-danger fs-6" asp-validation-for="VeiculoId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Veículo</label>
                <select class="form-control mb-1" asp-for="VeiculoId" asp-items="Model.Veiculos">
                    @if (Model.Veiculos is null || !Model.Veiculos.Any())
                    {
                        <option value="0" disabled>Nenhum veículo disponível</option>
                    }
                </select>
                <span class="text-danger fs-6" asp-validation-for="VeiculoId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Condutor</label>
                <select class="form-control mb-1" asp-for="CondutorId" asp-items="Model.Condutores">
                    @if (Model.Condutores is null || !Model.Condutores.Any())
                    {
                        <option value="0" disabled>Nenhum condutor disponível</option>
                    }
                </select>
                <span class="text-danger fs-6" asp-validation-for="CondutorId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Tipo de Plano</label>
                <select class="form-control mb-1" asp-for="TipoPlano" asp-items="Html.GetEnumSelectList<TipoPlanoCobrancaEnum>()"></select>
                <span class="text-danger fs-6" asp-validation-for="TipoPlano"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Marcador de Combustível</label>
                <select class="form-control mb-1" asp-for="MarcadorCombustivel" asp-items="Html.GetEnumSelectList<MarcadorCombustivelEnum>()" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="MarcadorCombustivel"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Quilometragem Percorrida</label>
                <input class="form-control mb-1" asp-for="QuilometragemPercorrida" type="number" readonly/>
                <span class="text-danger fs-6" asp-validation-for="QuilometragemPercorrida"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Data da Locação</label>
                <input class="form-control mb-1" asp-for="DataLocacao" type="date" min="@DateTime.Today"/>
                <span class="text-danger fs-6" asp-validation-for="DataLocacao"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Data Prevista de Devolução</label>
                <input class="form-control mb-1" asp-for="DevolucaoPrevista" type="date" min="@DateTime.Today"/>
                <span class="text-danger fs-6" asp-validation-for="DevolucaoPrevista"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Taxas Selecionadas</label>
                <select class="form-control mb-1" asp-for="TaxasSelecionadas" asp-items="Model.Taxas" multiple></select>
                <span class="text-danger fs-6" asp-validation-for="TaxasSelecionadas"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraDeVeiculos.Web/Views/Aluguel/Listar.cshtml
@model IEnumerable<ListarAluguelViewModel>

@{
    ViewBag.Title = "Listagem de Aluguéis";
}

<div class="col">

    <a class="btn btn-primary px-4 mt-3" asp-controller="Aluguel" asp-action="Inserir">
        <i class="bi bi-circle-add"></i>
        Inserir Novo Aluguel
    </a>

    <div class="row gap-2 my-3 my-xl-5">
        @foreach (var aluguelVm in Model)
        {
        <div class="card col-lg-4 col-xl-3 px-0">
            <div class="card-header bg-transparent d-flex justify-content-between align-items-center">
                <h5 class="p-0">Aluguel #@aluguelVm.Id</h5>

                <div class="text-end d-flex align-items-center gap-3">
                  @*   @if (!aluguelVm.DataDevolucao.HasValue)
                    {
                        <a title="Realizar Devolução"
                           class="text-info-emphasis fs-5"
                           href="/Aluguel/RealizarDevolucao/@aluguelVm.Id">
                            <i class="bi bi-coin"></i>
                        </a>
                    } *@
                  @*   <a title="Detalhes"
                       class="text-info-emphasis fs-5"
                       href="/Aluguel/Detalhes/@aluguelVm.Id">
                        <i class="bi bi-search"></i>
                    </a> *@
                 @*    @if (!aluguelVm.DataDevolucao.HasValue)
                    {
                        <a title="Editar"
                           class="text-info-emphasis fs-5"
                           href="/Aluguel/Editar/@aluguelVm.Id">
                            <i class="bi bi-pencil"></i>
                        </a>    
                    } *@
                  @*   @if (aluguelVm.DataDevolucao.HasValue)
                    {
                        <a title="Excluir"
                           class="text-info-emphasis fs-5" href="/Aluguel/Excluir/@aluguelVm.Id">
                            <i class="bi bi-trash-fill"></i>
                        </a>
                    } *@
                </div>
            </div>

            <div class="card-body">
                <h5 class="card-title">Veículo: @aluguelVm.Veiculo</h5>
                <p class="card-text">
                    Data Locação: @aluguelVm.DataLocacao <br />
                    Cliente: @aluguelVm.Cliente <br />

                    <hr>
                </p>
            </div>
        </div>
        }
    </div>
</div>

LocadoraDeVeiculos.Web/Views/Aluguel/RealizarDevolucao.cshtml
@using LocadoraDeVeiculos.Dominio.ModuloLocacao
@using Microsoft.AspNetCore.Mvc.TagHelpers

@model RealizarDevolucaoViewModel

@{
    ViewBag.Title = "Realizar Devolução de Aluguel";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="RealizarDevolucao">

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Id</label>
                <input class="form-control mb-1" asp-for="Id" readonly/>
            </div>
            
            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Veículo</label>
                <select class="form-control mb-1" asp-for="VeiculoId" asp-items="Model.Veiculos" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="VeiculoId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Condutor</label>
                <select class="form-control mb-1" asp-for="CondutorId" asp-items="Model.Condutores" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="CondutorId"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Tipo de Plano</label>
                <select class="form-control mb-1" asp-for="TipoPlano" asp-items="Html.GetEnumSelectList<TipoPlanoCobrancaEnum>()" readonly></select>
                <span class="text-danger fs-6" asp-validation-for="TipoPlano"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Marcador de Combustível</label>
                <select class="form-control mb-1" asp-for="MarcadorCombustivel" asp-items="Html.GetEnumSelectList<MarcadorCombustivelEnum>()"></select>
                <span class="text-danger fs-6" asp-validation-for="MarcadorCombustivel"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Quilometragem Percorrida</label>
                <input class="form-control mb-1" asp-for="QuilometragemPercorrida" type="number"/>
                <span class="text-danger fs-6" asp-validation-for="QuilometragemPercorrida"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Data da Locação</label>
                <input class="form-control mb-1" asp-for="DataLocacao" type="date" readonly/>
                <span class="text-danger fs-6" asp-validation-for="DataLocacao"></span>
            </div>

            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Data Prevista de Devolução</label>
                <input class="form-control mb-1" asp-for="DevolucaoPrevista" type="date" readonly/>
                <span class="text-danger fs-6" asp-validation-for="DevolucaoPrevista"></span>
            </div>
  
            <div class="form-group">
                <label class="control-label fw-semibold mb-1">Taxas Selecionadas</label>
                <select class="form-control mb-1" asp-for="TaxasSelecionadas" asp-items="Model.Taxas" multiple></select>
                <span class="text-danger fs-6" asp-validation-for="TaxasSelecionadas"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>

LocadoraDeVeiculos.Web/Views/Aluguel/_Informacoes.cshtml
@model DetalhesAluguelViewModel

<div class="row gap-3 my-3 my-xl-5">
    <label class="fs-4"><strong>Cliente:</strong> @Model.Cliente</label>
  
    <label class="fs-4"><strong>Veículo:</strong> @Model.Veiculo</label>

    <label class="fs-4"><strong>Condutor:</strong> @Model.Condutor</label>

    <label class="fs-4"><strong>Tipo de Plano:</strong> @Model.TipoPlano</label>

    <label class="fs-4"><strong>Marcador de Combustível:</strong> @Model.MarcadorCombustivel</label>

    <label class="fs-4"><strong>Quilometragem Percorrida:</strong> @Model.QuilometragemPercorrida km</label>

    <label class="fs-4"><strong>Data de Locação:</strong> @Model.DataLocacao.ToShortDateString()</label>

    <label class="fs-4"><strong>Devolução Prevista:</strong> @Model.DevolucaoPrevista.ToShortDateString()</label>

    @if(Model.DataDevolucao.HasValue)
    {
        <label class="fs-4"><strong>Data de Devolução:</strong> @Model.DataDevolucao.Value.ToShortDateString()</label>
    }
    else
    {
        <label class="fs-4"><strong>Data de Devolução:</strong> Não devolvido</label>
    }

    <label class="fs-5"><strong>Id:</strong> [@Model.Id]</label>
</div>