LocadoraDeVeiculos.Web/Models/TaxaEServicoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LocadoraDeVeiculos.Web.Models
{
    public class InserirTaxaEServicoViewModel
    {
        [Required(ErrorMessage = "O nome é obrigatório")]
        [MinLength(3, ErrorMessage = "O nome deve conter ao menos 3 caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "A seleção de cobrança é obrigatório")]
        public string FixoOuDiario { get; set; }

        [Range(0.01, double.MaxValue, ErrorMessage = "O preço deve ser maior que zero")]
        public decimal Preco { get; set; }
    }

    public class EditarTaxaEServicoViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O nome é obrigatório")]
        [MinLength(3, ErrorMessage = "O nome deve conter ao menos 3 caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "A seleção de cobrança é obrigatório")]
        public string FixoOuDiario { get; set; }

        [Range(0.01, double.MaxValue, ErrorMessage = "O preço deve ser maior que zero")]
        public decimal Preco { get; set; }
    }

    public class ListarTaxaEServicoViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string FixoOuDiario { get; set; }
        public decimal Preco { get; set; }
    }

    public class DetalhesTaxaEServicoViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string FixoOuDiario { get; set; }
        public decimal Preco { get; set; }
    }
}

LocadoraDeVeiculos.Web/Controllers/TaxaEServicoController.cs
using AutoMapper;
using LocadoraDeVeiculos.Dominio.ModuloGrupoDeAutomoveis;
using LocadoraDeVeiculos.Dominio.ModuloTaxaEServico;
using LocadoraDeVeiculos.Service.Servicos;
using LocadoraDeVeiculos.Web.Aplicacao.Servicos;
using LocadoraDeVeiculos.Web.Extensions;
using LocadoraDeVeiculos.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace LocadoraDeVeiculos.Web.Controllers
{
    public class TaxaEServicoController : WebControllerBase
    {
        private readonly TaxaEServicoService servicoTaxaEServico;
        private readonly IMapper mapeador;

        public TaxaEServicoController(TaxaEServicoService servicoTaxaEServico, IMapper mapeador)
        {
            this.servicoTaxaEServico = servicoTaxaEServico;
            this.mapeador = mapeador;
        }

        public IActionResult Listar()
        {
            var resultado =
                servicoTaxaEServico.SelecionarTodos(UsuarioId.GetValueOrDefault());

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction("Index", "Home");
            }

            var taxaEServicos = resultado.Value;

            var listarTaxasEServicoViewModel
                = mapeador.Map<IEnumerable<ListarTaxaEServicoViewModel>>(taxaEServicos);

            ViewBag.Mensagem = TempData.DesserializarMensagemViewModel();

            return View(listarTaxasEServicoViewModel);
        }

        public IActionResult Inserir()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Inserir(InserirTaxaEServicoViewModel inserirTaxaEServicoVm)
        {
            if (!ModelState.IsValid)
                return View(inserirTaxaEServicoVm);

            var novaTaxaEServico = mapeador.Map<TaxaEServico>(inserirTaxaEServicoVm);

            novaTaxaEServico.UsuarioId = UsuarioId.GetValueOrDefault();

            var resultado = servicoTaxaEServico.Inserir(novaTaxaEServico);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof(Listar));
            }

            ApresentarMensagemSucesso($"O registro ID [{novaTaxaEServico.Id}] foi inserido com sucesso!");

            return RedirectToAction(nameof(Listar));
        }

        public IActionResult Editar(int id)
        {
            var resultado = servicoTaxaEServico.SelecionarPorId(id);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof(Listar));
            }

            var taxaEServico = resultado.Value;

            var editarTaxaEServicoVm = mapeador.Map<EditarTaxaEServicoViewModel>(taxaEServico);

            return View(editarTaxaEServicoVm);
        }

        [HttpPost]
        public IActionResult Editar(EditarTaxaEServicoViewModel editarTaxaEServicoVm)
        {
            if (!ModelState.IsValid)
                return View(editarTaxaEServicoVm);

            var taxaEServico = mapeador.Map<TaxaEServico>(editarTaxaEServicoVm);

            var resultado = servicoTaxaEServico.Editar(taxaEServico);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof(Listar));
            }

            ApresentarMensagemSucesso($"O registro ID [{taxaEServico.Id}] foi editado com sucesso!");

            return RedirectToAction(nameof(Listar));
        }

        public IActionResult Excluir(int id)
        {
            var resultado = servicoTaxaEServico.SelecionarPorId(id);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof(Listar));
            }

            var taxaEServico = resultado.Value;

            var detalhesTaxaEServicoViewModel = mapeador.Map<DetalhesTaxaEServicoViewModel>(taxaEServico);

            return View(detalhesTaxaEServicoViewModel);
        }

        [HttpPost]
        public IActionResult Excluir(DetalhesTaxaEServicoViewModel detalhesTaxaEServicoViewModel)
        {
            var resultado = servicoTaxaEServico.Excluir(detalhesTaxaEServicoViewModel.Id);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado);

                return RedirectToAction(nameof(Listar));
            }

            ApresentarMensagemSucesso($"O registro ID [{detalhesTaxaEServicoViewModel.Id}] foi excluído com sucesso!");

            return RedirectToAction(nameof(Listar));
        }

        public IActionResult Detalhes(int id)
        {
            var resultado = servicoTaxaEServico.SelecionarPorId(id);

            if (resultado.IsFailed)
            {
                ApresentarMensagemFalha(resultado.ToResult());

                return RedirectToAction(nameof(Listar));
            }

            var taxaEServico = resultado.Value;

            var detalhesTaxaEServicoViewModel = mapeador.Map<DetalhesTaxaEServicoViewModel>(taxaEServico);

            return View(detalhesTaxaEServicoViewModel);
        }
    }
}

LocadoraDeVeiculos.Web/Views/TaxaEServico/Detalhes.cshtml
@model DetalhesTaxaEServicoViewModel

@{
    ViewBag.Title = "Detalhes das Taxas e Serviços";
}

<div class="col">
    <partial name="_Informacoes" model="Model"></partial>

    <a asp-action="Listar" class="btn btn-outline-primary px-5 mt-5">
        <i class="bi bi-arrow-return-left me-1"></i>
        Voltar
    </a>
</div>

LocadoraDeVeiculos.Web/Views/TaxaEServico/Editar.cshtml
@using LocadoraDeVeiculos.Dominio.ModuloTaxaEServico
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model EditarTaxaEServicoViewModel

@{
    ViewBag.Title = "Editar Taxas e Serviços";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="Editar">
            <div>
                <label class="control-label fw-semibold mb-1">Nome</label>
                <input class="form-control mb-1" asp-for="Nome"/>
                <span class="text-danger fs-6" asp-validation-for="Nome"></span>
            </div>
            
            <div>
                <label class="control-label fw-semibold mb-1">Método de Cobrança</label>
                <select class="form-control mb-1" asp-for="FixoOuDiario" asp-items="Html.GetEnumSelectList<FIxoOuDiario>()"></select>
                <span class="text-danger fs-6" asp-validation-for="FixoOuDiario"></span>
            </div>
            
            <div>
                <label class="control-label fw-semibold mb-1">Preço:</label>
                <input class="form-control mb-1" asp-for="Preco" id="preco" oninput="formatarPreco(this)" />
                <span class="text-danger fs-6" asp-validation-for="Preco"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" href="/TaxaEServico/Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>
<script>
    function formatarPreco(element) {
        let valor = element.value;
        valor = valor.replace(/\D/g, "");
        valor = (valor / 100).toFixed(2) + "";
        valor = valor.replace(".", ",");
        valor = valor.replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1.");
        element.value = valor;
    }
</script>

LocadoraDeVeiculos.Web/Views/TaxaEServico/Excluir.cshtml
@model DetalhesGrupoAutomoveisViewModel

@{
    ViewBag.Title = "Excluir Taxas e Serviços";
}

<div class="col">
    <partial name="_Informacoes" model="Model"></partial>

    <form class="d-grid gap-2 d-md-block mt-5" asp-action="Excluir">
        <button class="btn btn-danger px-5">
            <i class="bi bi-trash-fill me-1"></i>
            Confirmar
        </button>

        <a class="btn btn-outline-primary px-5" asp-action="Listar">
            <i class="bi bi-arrow-return-left me-1"></i>
            Voltar
        </a>
    </form>
</div>

LocadoraDeVeiculos.Web/Views/TaxaEServico/Inserir.cshtml
@using LocadoraDeVeiculos.Dominio.ModuloTaxaEServico
@model InserirTaxaEServicoViewModel

@{
    ViewBag.Title = "Inserir Taxas e Serviços";
}

<div class="col">
    <div class="row gap-3 my-3 my-xl-5">
        <form class="col-lg-6 d-grid gap-3 fs-5" asp-action="Inserir">
            <div>
                <label class="control-label fw-semibold mb-1">Nome</label>
                <input class="form-control mb-1" asp-for="Nome"/>
                <span class="text-danger fs-6" asp-validation-for="Nome"></span>
            </div>
            
            <div>
                <label class="control-label fw-semibold mb-1">Método de Cobrança</label>
                <select class="form-control mb-1" asp-for="FixoOuDiario" asp-items="Html.GetEnumSelectList<FIxoOuDiario>()"></select>
                <span class="text-danger fs-6" asp-validation-for="FixoOuDiario"></span>
            </div>
            
            <div>
                <label class="control-label fw-semibold mb-1">Preço:</label>
                <input class="form-control mb-1" asp-for="Preco" id="preco" oninput="formatarPreco(this)" />
                <span class="text-danger fs-6" asp-validation-for="Preco"></span>
            </div>

            <div class="d-grid gap-2 d-md-block mt-4">
                <button class="btn btn-primary px-5">
                    <i class="bi bi-floppy-fill me-1"></i>
                    Gravar
                </button>

                <a class="btn btn-outline-primary px-5" asp-action="Listar">
                    <i class="bi bi-arrow-return-left me-1"></i>
                    Voltar
                </a>
            </div>
        </form>
    </div>
</div>
<script>
    function formatarPreco(element) {
        let valor = element.value;
        valor = valor.replace(/\D/g, "");
        valor = (valor / 100).toFixed(2) + "";
        valor = valor.replace(".", ",");
        valor = valor.replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1.");
        element.value = valor;
    }
</script>

LocadoraDeVeiculos.Web/Views/TaxaEServico/Listar.cshtml
@model IEnumerable<ListarTaxaEServicoViewModel>

@{
    ViewBag.Title = "Listagem de Taxas e Serviços";
}

<div class="col">

    <a class="btn btn-primary px-4 mt-3" asp-controller="TaxaEServico" asp-action="Inserir">
        <i class="bi bi-circle-add"></i>
        Inserir Nova Taxa ou Serviço
    </a>

    <div class="row gap-2 my-3 my-xl-5">
        @foreach (var grupoVm in Model)
        {
            <div class="card col-lg-4 col-xl-3">
                <div class="card-header bg-transparent d-flex justify-content-between align-items-center">
                    <h5 class="p-0">@grupoVm.Id</h5>

                    <div class="text-end d-flex align-items-center gap-3">
                        <a title="Detalhes"
                           class="text-info-emphasis fs-5"
                           href="/TaxaEServico/Detalhes/@grupoVm.Id">
                            <i class="bi bi-search"></i>
                        </a>
                        <a title="Editar"
                           class="text-info-emphasis fs-5"
                           href="/TaxaEServico/Editar/@grupoVm.Id">
                            <i class="bi bi-pencil-fill"></i>
                        </a>
                        <a title="Excluir"
                           class="text-info-emphasis fs-5" href="/TaxaEServico/Excluir/@grupoVm.Id">
                            <i class="bi bi-trash-fill"></i>
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <h5 class="card-title">@grupoVm.Nome</h5>
                    <p class="card-text">
                        Método De Cobrança: @grupoVm.FixoOuDiario <br />
                        Preço: @grupoVm.Preco
                    </p>
                </div>
            </div>
        }
    </div>
</div>

LocadoraDeVeiculos.Web/Views/TaxaEServico/_Informacoes.cshtml
@model DetalhesTaxaEServicoViewModel

<div class="row gap-3 my-3 my-xl-5">
    <label class="fs-4"><strong>Taxa/Serviço:</strong> @Model.Nome</label>
    <label class="fs-4"><strong>Método de Cobrança:</strong> @Model.FixoOuDiario</label>
    <label class="fs-4"><strong>Preço:</strong> @Model.Preco</label>

    <label class="fs-5"><strong>Id:</strong> [@Model.Id]</label>
</div>